// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetCare.Services;

#nullable disable

namespace PetCare.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetCare.Models.Chitietdon", b =>
                {
                    b.Property<int>("id_chitietdh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_chitietdh"));

                    b.Property<int>("id_dh")
                        .HasColumnType("int");

                    b.Property<int>("id_sp")
                        .HasColumnType("int");

                    b.Property<int>("soluong")
                        .HasColumnType("int");

                    b.HasKey("id_chitietdh");

                    b.HasIndex("id_dh");

                    b.ToTable("Chitietdons");
                });

            modelBuilder.Entity("PetCare.Models.Chitietlich", b =>
                {
                    b.Property<int>("id_ctlich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_ctlich"));

                    b.Property<string>("ghichu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_dichvu")
                        .HasColumnType("int");

                    b.Property<int>("id_lich")
                        .HasColumnType("int");

                    b.HasKey("id_ctlich");

                    b.ToTable("Chitietlichs");
                });

            modelBuilder.Entity("PetCare.Models.DichVu", b =>
                {
                    b.Property<int>("id_dichvu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_dichvu"));

                    b.Property<int>("loai_dichvu")
                        .HasColumnType("int");

                    b.Property<string>("ten_dichvu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_dichvu");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("PetCare.Models.DichVu_CanNang", b =>
                {
                    b.Property<int>("id_dichvu_can_nang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_dichvu_can_nang"));

                    b.Property<decimal>("gia_thanh")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<int>("id_dichvu")
                        .HasColumnType("int");

                    b.Property<float>("max_can_nang")
                        .HasColumnType("real");

                    b.Property<float>("min_can_nang")
                        .HasColumnType("real");

                    b.HasKey("id_dichvu_can_nang");

                    b.ToTable("DichVu_CanNangs");
                });

            modelBuilder.Entity("PetCare.Models.DichVu_Ngay", b =>
                {
                    b.Property<int>("id_dichvu_ngay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_dichvu_ngay"));

                    b.Property<decimal>("gia_thanh")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<int>("id_dichvu")
                        .HasColumnType("int");

                    b.HasKey("id_dichvu_ngay");

                    b.ToTable("DichVu_Ngays");
                });

            modelBuilder.Entity("PetCare.Models.Donhang", b =>
                {
                    b.Property<int>("id_dh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_dh"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("diachi_giao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghi_chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_kh")
                        .HasColumnType("int");

                    b.Property<int>("id_nv")
                        .HasColumnType("int");

                    b.Property<string>("ma_dh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("tong_tien")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_dh");

                    b.HasIndex("id_kh");

                    b.ToTable("Donhangs");
                });

            modelBuilder.Entity("PetCare.Models.Khachhang", b =>
                {
                    b.Property<int>("id_kh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_kh"));

                    b.Property<string>("diachi_kh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("matkhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("sdt_kh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ten_kh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_kh");

                    b.ToTable("Khachhangs");
                });

            modelBuilder.Entity("PetCare.Models.Khohang", b =>
                {
                    b.Property<int>("id_kho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_kho"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_sp")
                        .HasColumnType("int");

                    b.Property<int>("soluong")
                        .HasColumnType("int");

                    b.HasKey("id_kho");

                    b.HasIndex("id_sp");

                    b.ToTable("Khohangs");
                });

            modelBuilder.Entity("PetCare.Models.Lichhen", b =>
                {
                    b.Property<int>("id_lichhen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_lichhen"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DichVuid_dichvu")
                        .HasColumnType("int");

                    b.Property<string>("ghi_chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_dichvu")
                        .HasColumnType("int");

                    b.Property<int>("id_kh")
                        .HasColumnType("int");

                    b.Property<int?>("id_nv")
                        .HasColumnType("int");

                    b.Property<int>("id_tc")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngay_hen")
                        .HasColumnType("datetime2");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_lichhen");

                    b.HasIndex("DichVuid_dichvu");

                    b.HasIndex("id_dichvu");

                    b.HasIndex("id_kh");

                    b.HasIndex("id_tc");

                    b.ToTable("Lichhens");
                });

            modelBuilder.Entity("PetCare.Models.Nhanvien", b =>
                {
                    b.Property<int>("id_nv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_nv"));

                    b.Property<string>("chucvu_nv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("email_nv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("matkhau_nv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt_nv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ten_nv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_nv");

                    b.ToTable("Nhanviens");
                });

            modelBuilder.Entity("PetCare.Models.Sanpham", b =>
                {
                    b.Property<int>("id_sanpham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_sanpham"));

                    b.Property<string>("hinhanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("id_loaisp")
                        .HasColumnType("int");

                    b.Property<string>("ma_sanpham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soluong")
                        .HasColumnType("int");

                    b.Property<string>("ten_sanpham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("thanhtien")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("id_sanpham");

                    b.HasIndex("id_loaisp");

                    b.ToTable("Sanphams");
                });

            modelBuilder.Entity("PetCare.Models.Sanpham_Loai", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("hinh_anh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Sanpham_loais");
                });

            modelBuilder.Entity("petCare.Models.Thucung", b =>
                {
                    b.Property<int>("id_pet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_pet"));

                    b.Property<float>("cannang_pet")
                        .HasMaxLength(100)
                        .HasColumnType("real");

                    b.Property<string>("giong_pet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("id_kh")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngaysinh_pet")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_pet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_pet");

                    b.HasIndex("id_kh");

                    b.ToTable("Thucungs");
                });

            modelBuilder.Entity("PetCare.Models.Chitietdon", b =>
                {
                    b.HasOne("PetCare.Models.Donhang", "Donhang")
                        .WithMany("Chitietdons")
                        .HasForeignKey("id_dh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donhang");
                });

            modelBuilder.Entity("PetCare.Models.Donhang", b =>
                {
                    b.HasOne("PetCare.Models.Khachhang", "Khachhang")
                        .WithMany("Donhangs")
                        .HasForeignKey("id_kh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khachhang");
                });

            modelBuilder.Entity("PetCare.Models.Khohang", b =>
                {
                    b.HasOne("PetCare.Models.Sanpham", "Sanpham")
                        .WithMany()
                        .HasForeignKey("id_sp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("PetCare.Models.Lichhen", b =>
                {
                    b.HasOne("PetCare.Models.DichVu", null)
                        .WithMany("Lichhens")
                        .HasForeignKey("DichVuid_dichvu");

                    b.HasOne("PetCare.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("id_dichvu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCare.Models.Khachhang", "Khachhang")
                        .WithMany("Lichhens")
                        .HasForeignKey("id_kh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("petCare.Models.Thucung", "Thucung")
                        .WithMany("Lichhens")
                        .HasForeignKey("id_tc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("Khachhang");

                    b.Navigation("Thucung");
                });

            modelBuilder.Entity("PetCare.Models.Sanpham", b =>
                {
                    b.HasOne("PetCare.Models.Sanpham_Loai", "sanpham_loai")
                        .WithMany()
                        .HasForeignKey("id_loaisp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sanpham_loai");
                });

            modelBuilder.Entity("petCare.Models.Thucung", b =>
                {
                    b.HasOne("PetCare.Models.Khachhang", "Khachhang")
                        .WithMany("Thucungs")
                        .HasForeignKey("id_kh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khachhang");
                });

            modelBuilder.Entity("PetCare.Models.DichVu", b =>
                {
                    b.Navigation("Lichhens");
                });

            modelBuilder.Entity("PetCare.Models.Donhang", b =>
                {
                    b.Navigation("Chitietdons");
                });

            modelBuilder.Entity("PetCare.Models.Khachhang", b =>
                {
                    b.Navigation("Donhangs");

                    b.Navigation("Lichhens");

                    b.Navigation("Thucungs");
                });

            modelBuilder.Entity("petCare.Models.Thucung", b =>
                {
                    b.Navigation("Lichhens");
                });
#pragma warning restore 612, 618
        }
    }
}
